/*
output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = aws_eks_cluster.main.kubeconfig
}
*/

output "eks_cluster_name" {
  description = "The name of the EKS Cluster"
  value = var.eks_cluster_name
}

output "eks_endpoint" {
  value = aws_eks_cluster.main.endpoint
}

output "eks_kubeconfig_certificate_authority_data" {
  value = aws_eks_cluster.main.certificate_authority[0].data
}

